name: Lab01 Variables and Secrets
run-name: Lab01 - ${{ github.actor }} is testing variables and secrets 🚀
permissions: read-all
on:
  workflow_dispatch:
jobs:
  example-job:
    env:
      MY_VARIABLE: "Hello, GitHub Actions!"
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        env:
          DEMO_SECRET: ${{ secrets.DEMO_SECRET }}

        run: |
          echo "This is my variable $MY_VARIABLE"
          echo "Secret Value: $DEMO_SECRET"
